version: "3"
services:
    osquery_ubuntu:
        image: niyue/osquery
        deploy:
            replicas: 3
            restart_policy:
                condition: on-failure
        extra_hosts:
            - "SplunkServerDefaultCert:172.17.0.1"
        command: ["--tls_hostname", "SplunkServerDefaultCert:8089", "--tls_server_certs", "/tmp/cacert.pem"]
    osquery_centos:
        image: niyue/osquery:centos
        deploy:
            replicas: 6
            restart_policy:
                condition: on-failure
        extra_hosts:
            - "SplunkServerDefaultCert:172.17.0.1"
        command: ["--tls_hostname", "SplunkServerDefaultCert:8089", "--tls_server_certs", "/tmp/cacert.pem"]
    osquery_centos6:
        image: niyue/osquery:centos6
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        extra_hosts:
            - "SplunkServerDefaultCert:172.17.0.1"
        command: ["--tls_hostname", "SplunkServerDefaultCert:8089", "--tls_server_certs", "/tmp/cacert.pem"]
            
